apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-engine.fullname" . }}-config
  labels:
    {{- include "order-engine.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.springProfilesActive | quote }}
  SERVER_PORT: {{ .Values.env.serverPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.env.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.datasource.username | quote }}
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.env.datasource.hikari.maximumPoolSize | quote }}
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: {{ .Values.env.datasource.hikari.minimumIdle | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_CONSUMER_GROUP_ID: {{ .Values.env.kafka.consumerGroupId | quote }}
  APP_OUTBOX_SCHEDULER_RATE_MS: {{ .Values.env.outbox.schedulerRateMs | quote }}
  APP_OUTBOX_BATCH_SIZE: {{ .Values.env.outbox.batchSize | quote }}
  APP_SAGA_TIMEOUT_THRESHOLD_SECONDS: {{ .Values.env.saga.timeoutThresholdSeconds | quote }}
  APP_SAGA_SCHEDULER_RATE_MS: {{ .Values.env.saga.schedulerRateMs | quote }}
  APP_SECURITY_ENABLED: {{ .Values.env.security.enabled | quote }}
  APP_RATELIMIT_ENABLED: {{ .Values.env.rateLimit.enabled | quote }}
  APP_RATELIMIT_STANDARD_CAPACITY: {{ .Values.env.rateLimit.standardCapacity | quote }}
  APP_RATELIMIT_ENTERPRISE_CAPACITY: {{ .Values.env.rateLimit.enterpriseCapacity | quote }}
  JAVA_TOOL_OPTIONS: {{ .Values.jvm.opts | quote }}
