apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-engine.fullname" . }}-secret
  labels:
    {{- include "order-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.datasource.password | quote }}
  APP_SECURITY_ADMIN_TOKEN: {{ .Values.env.security.adminToken | quote }}
  APP_SECURITY_OPS_TOKEN: {{ .Values.env.security.opsToken | quote }}
